#!/usr/bin/env bash
set -euo pipefail

python3 << 'EOF'
import json, os, sys
from collections import Counter

if not os.path.exists('discord.har'):
	sys.exit('ERROR: drop discord.har here first')

print('Reading discord.har...')
raw = []
for e in json.load(open('discord.har', encoding='utf-8')).get('log', {}).get('entries', []):
	url = e.get('request', {}).get('url', '')
	if 'applications' not in url and 'detectable' not in url:
		continue
	try:
		data = json.loads(e['response']['content'].get('text', ''))
		items = data if isinstance(data, list) else data.get('items', data.get('applications', []))
		for item in items:
			n, i = item.get('name'), item.get('id') or item.get('applicationId')
			if n and i:
				raw.append((n, i))
	except Exception:
		pass

name_count = Counter(n for n, _ in raw)
pairs = {}
for n, i in raw:
	key = f"{n} [{i}]" if name_count[n] > 1 else n
	pairs[key] = i

dupes = sum(1 for c in name_count.values() if c > 1)
print(f'{len(pairs)} games ({dupes} duplicate names disambiguated with their ID)')

os.makedirs('MimicRPC', exist_ok=True)
data = '\n'.join(f'{k.replace("|", "")}|{v}' for k, v in pairs.items())
Q = '"""'

cs = f"""\
// <auto-generated>
using System.Collections.Generic;

static class GameDb
{{
	static readonly string _raw = {Q}
{data}
{Q};

	public static readonly Dictionary<string, string> Db;
	public static readonly string[] Names;

	static GameDb()
	{{
		Db = new(StringComparer.OrdinalIgnoreCase);
		foreach (var line in _raw.Split('\\n', System.StringSplitOptions.RemoveEmptyEntries))
		{{
			var i = line.IndexOf('|');
			if (i > 0) Db[line[..i]] = line[(i + 1)..];
		}}
		Names = [.. Db.Keys];
	}}
}}
"""

open('MimicRPC/GameDb.GENERATED.cs', 'w', encoding='utf-8').write(cs)
print(f'Written MimicRPC/GameDb.GENERATED.cs ({len(pairs)} entries)')
EOF